name: Build and Push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: main

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        working-directory: ./main
        run: |
          yarn install --frozen-lockfile
      - name: Build React App
        working-directory: ./main
        env:
          SYNC_ADDRESS: ${{ vars.SYNC_ADDRESS }}
          DEFAULT_SOURCE_ADDRESS: ${{ vars.DEFAULT_SOURCE_ADDRESS }}
        run: |
          yarn run build

      - name: Checkout Static Repository
        uses: actions/checkout@v4
        with:
          ref: static
          path: static

      - name: Copy the Git folder
        run: |
          cp -r ./static/.git ./main/build/

      - name: Add and commit
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          cwd: ./main/build/
